version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
    expose:
      - 2181
    networks:
      - kafka-demo-network

  kafka:
    image: wurstmeister/kafka
    hostname: kafka
    restart: always
    depends_on:
      - zookeeper
    expose:
      - 9092
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 'localhost'
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "demo-images:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - kafka-demo-network

networks:
  kafka-demo-network: ~